language: node_js
node_js: "10.4.1"
deploy:
  provider: heroku
  api_key:
    secure: "lqPFGs0BKs2R9+dGWn/hCkmV6kIjTRQ8NKFFb+meLRrMY+axMzfM88BgswMnsc9FaxQTVIogA+6SChpAdAHQKX3tvDANFfkuIyf329plI7xas/dzJy8vuDoPaUvonPu3w1WOiORMcH2FCedG8roVDnBS7bZX0Ngr1TXe9ynXBxRxGwvRKi0VDmnJJdwaAS/slacRA5r22hh1ytTlr2HqcdiEL19HEdXbJmiEBgbb0Zla6Ctnt0nTc+1IILQFIXx5cyZTMGuMR+Ube1S/bTW5VNJ1zI7FtecPijVNhB18+KqZLkhK3mpeq1T6vsKc8Ux5YGLPzclHx4KLxtgJeLf9Q0dG2u+hC4vEGXw+mnxwrewQ42H8I4r3Ut/nhcgjNihGGBuF+kMlHy9X3oLYR1Dd2WcnGirouYuJMKXua+LH2OFT185c0e5BWdIFc3fIeqEIRiKs+jRCj7bfkx/VDo+LJCOtSABKK94q0p9g6ReIrkbF8P8O0u/vuAV5350zPBt1NdP68zeTy/vALTCoCntHvUWgP6u5/6WGWevarxiCjFKNPuJfXSxfRfdx38gRB5cADUCXxjIMeHkXkX0WcXqdX3W2ODafEJabRXUNM/s9UJVCrLWoVpnySYNkmBhdpWlg4HTOC3v3fhA4HnTbzzgU5mmHb1kYRiDwIBCoqQaLEwo="
  app: alenvi-api-dev
addons:
  apt:
    packages:
    - mongodb-org
services: mongodb