# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit and integration tests

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017

    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      # Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 22.20.0
      - run: yarn install
      - run: npm run build --if-present
      - run: npm test
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          DETACHMENT_ALLOWED_COMPANY_IDS: ${{ secrets.DETACHMENT_ALLOWED_COMPANY_IDS }}
          VAEI_SUBPROGRAM_IDS: ${{ secrets.VAEI_SUBPROGRAM_IDS }}
          REAL_ELEARNING_DURATION_SUBPROGRAM_IDS: ${{ secrets.REAL_ELEARNING_DURATION_SUBPROGRAM_IDS }}
          TRAINER_FEES_BILLING_ITEM: ${{ secrets.TRAINER_FEES_BILLING_ITEM }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
